DROP TABLE IF EXISTS CONFIG;

CREATE TABLE CONFIG
(   
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    APPLICATION VARCHAR(100),
    PROFILE VARCHAR(100),
    LABEL VARCHAR(100),
    NAME VARCHAR(1024),
    VALUE VARCHAR(1024) 
);
DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PATH VARCHAR(100) NOT NULL,
    SERVICE_ID VARCHAR(200) NOT NULL,
    URL VARCHAR(1024),
    STRIP_PREFIX VARCHAR(100)
);