DROP TABLE IF EXISTS CONFIG;

CREATE TABLE CONFIG
(   
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    SYSTEM_CODE VARCHAR(100),
    PROFILE VARCHAR(100),
    LABEL VARCHAR(100),
    NAME VARCHAR(1024),
    VALUE VARCHAR(1024),
    REMARK VARCHAR(500)
);
DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PATH VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL,
    URL VARCHAR(1024),
    STRIP_PREFIX VARCHAR(100)
);

DROP TABLE IF EXISTS APPLICATION;

CREATE TABLE APPLICATION
(
    ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    SYSTEM_CODE VARCHAR(100) NOT NULL UNIQUE,
    OWNER VARCHAR(100) NOT NULL,
    CREATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);